### ISSUE TITLE
Unable to Build Environment

### ISSUE THREAD

**Issue by inferno46n2** [cnnlstm/DiffusionMat#4]
When I try to build the conda environment I am getting the errors below

Steps I am using:
1) Open anaconda CMD
2) CD to DiffusionMat Folder
3) Run your provided environment building script

![image](https://github.com/cnnlstm/DiffusionMat/assets/73665023/9cf20aa0-5b2f-4363-93ca-37fb47c42cf1)

**Comment by cnnlstm** [comment]
I have updated a new environment, please build the environment again.

**Comment by inferno46n2** [comment]
> I have updated a new environment, please build the environment again.

![image](https://github.com/cnnlstm/DiffusionMat/assets/73665023/02d7387f-2270-40ef-be98-d8d60ec3e68e)

I did a git clone before trying so I should have the latest. You have a space in your yaml file title. I fixed on my end but you should fix on yours so others do not encounter this error.

**Comment by inferno46n2** [comment]
Similar error to last time except much less errors this time...
![image](https://github.com/cnnlstm/DiffusionMat/assets/73665023/3c9ddff4-60bd-4267-9408-b17576e80466)

**Comment by cnnlstm** [comment]
It sees you build the environment on Windows, Anaconda on Ubuntu is recommended. But you may try to delete those not found packages, and install them manually if needed.
